package view;

import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import model.Familia;
import model.Persona;
import model.Serialize;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ArmandoPC
 */
public class ArbolForm extends javax.swing.JFrame {

    Familia arbol;
    File file = null;
    ImageIcon Imagen = new ImageIcon();
    Path TO;
    Serialize se = new Serialize();

    /**
     * Creates new form ArbolForm
     */
    public ArbolForm() {
        arbol = new Familia();
        initComponents();
        this.btnAddRaiz.setVisible(false);
        String to = System.getProperty("user.dir"); // recupero el directorio del proyecto
        String separator = System.getProperty("file.separator"); //recupero el separador ex: Windows= '\' , Linux='/'
        to = to + separator + "src" + separator + "src" + separator + "dataarbol.xml"; // concateno la ruta destino
        File f = new File(to);
        if (f.exists()) {
            Persona leernodo = se.ReadXml();
            arbol.setRaiz(leernodo);
            this.label.setIcon(arbol.GenerateImg());
            arbol.verHijosRecursivo(arbol.getRaiz());
            this.LlenarCombo(arbol.getListaPesona());

        } else {
            this.btnAddHijo.setEnabled(false);
            this.comboboxPadre.setEnabled(false);
            this.textHijo.setEnabled(false);
            this.btnAddRaiz.setVisible(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        panelImagen = new javax.swing.JLayeredPane();
        label = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        comboboxPadre = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        textHijo = new javax.swing.JTextField();
        btnAddHijo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAddRaiz = new javax.swing.JButton();
        contenImg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImagen.setLayer(label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBackground(new java.awt.Color(153, 153, 153));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Padre:");

        comboboxPadre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxPadreActionPerformed(evt);
            }
        });

        jLabel2.setText("Hijo:");

        btnAddHijo.setText("Añadir Hijo");
        btnAddHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHijoActionPerformed(evt);
            }
        });

        jLabel3.setText("Arbol Genealógico");

        btnAddRaiz.setText("Añadir Raiz");
        btnAddRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRaizActionPerformed(evt);
            }
        });

        contenImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Selecione Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnAddHijo))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddRaiz)))
                .addGap(57, 57, 57))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHijo)
                    .addComponent(comboboxPadre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(contenImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddHijo, btnAddRaiz});

        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenImg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddHijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddRaiz)
                .addGap(74, 74, 74))
        );
        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(comboboxPadre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(textHijo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAddHijo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAddRaiz, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(contenImg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane2)
                    .addComponent(panelImagen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxPadreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboboxPadreActionPerformed

    private void btnAddHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHijoActionPerformed
        // TODO add your handling code here:
        if (file != null) {
            String padre = this.comboboxPadre.getSelectedItem().toString();
            String hijo = this.textHijo.getText();
            if (hijo.length() > 0) {
                arbol.addHijoRecursivo(arbol.getRaiz(), hijo, TO.toString(), padre);
                arbol.setListaPesona(new ArrayList<Persona>());
                arbol.verHijosRecursivo(arbol.getRaiz());
                this.LlenarCombo(arbol.getListaPesona());
                this.textHijo.setText("");
                try {
                    arbol.generarArchivo(arbol.generateFileData(arbol.getRaiz()));
                    this.label.setIcon(arbol.GenerateImg());
                    se.writeXml(arbol.getRaiz());
                } catch (IOException ex) {
                    Logger.getLogger(ArbolForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this.getRootPane(), "Ingrese nombre de hijo");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Elija una imagen");
        }

    }//GEN-LAST:event_btnAddHijoActionPerformed

    private void btnAddRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRaizActionPerformed
        // TODO add your handling code here:
        if (file != null) {
            String raiz = JOptionPane.showInputDialog(this.getRootPane(), "Ingrese Raiz");
            if (raiz.length() > 0) {
                System.out.println(TO.toString());
                arbol.setRaiz(new Persona(raiz, TO.toString()));
                this.btnAddHijo.setEnabled(true);
                this.btnAddRaiz.setEnabled(false);
                this.comboboxPadre.setEnabled(true);
                this.textHijo.setEnabled(true);
                arbol.verHijosRecursivo(arbol.getRaiz());
                this.btnAddRaiz.setVisible(false);
                this.LlenarCombo(arbol.getListaPesona());
                try {
                    arbol.generarArchivo(arbol.generateFileData(arbol.getRaiz()));
                    this.label.setIcon(arbol.GenerateImg());

                    se.writeXml(arbol.getRaiz());
                } catch (IOException ex) {
                    Logger.getLogger(ArbolForm.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this.getRootPane(), "Error al ingresar raiz");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Elija una imagen");
        }
    }//GEN-LAST:event_btnAddRaizActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public String getDescription() {
                return "All supported image formats";
            }

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".png")
                            || f.getName().toLowerCase().endsWith(".jpeg")
                            || f.getName().toLowerCase().endsWith(".jpg")
                            || f.getName().toLowerCase().endsWith(".gif");
                }
            }
        });
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // JFileChooserEx is the name of the JFrameForm/Java class
        int res = chooser.showOpenDialog(ArbolForm.this);

        if (res == JFileChooser.APPROVE_OPTION) {
            file = chooser.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getAbsolutePath());
            String to = System.getProperty("user.dir"); // recupero el directorio del proyecto
            String separator = System.getProperty("file.separator"); //recupero el separador ex: Windows= '\' , Linux='/'
            String imgname = "";
            String[] split;
            split = file.getAbsolutePath().split(separator + separator);
            imgname = split[split.length - 1];// recupero el nombre de la imagen
            to = to + separator + "src" + separator + "src" + separator + imgname; // concateno la ruta destino
            Path FROM = Paths.get(file.getAbsolutePath());
            TO = Paths.get(to);
            //sobreescribir el fichero de destino, si existe, y copiar
            // los atributos, incluyendo los permisos rwx
            CopyOption[] options = new CopyOption[]{
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.COPY_ATTRIBUTES
            };
            try {
                Files.copy(FROM, TO, options);// copio la imagen al nuevo directorio
                // Get width and height of picLabel
                Rectangle rect = this.contenImg.getBounds();
                // Scaling the Image to fit in the picLabel
                Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
                // Converting the image back to ImageIcon to make it acceptable by picLabel
                image = new ImageIcon(scaledImage);
                this.contenImg.setIcon(image);

            } catch (IOException ex) {
                Logger.getLogger(ArbolForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void LlenarCombo(List<Persona> g) {
        this.comboboxPadre.removeAllItems();
        for (Persona es : g) {
            this.comboboxPadre.addItem(es);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHijo;
    private javax.swing.JButton btnAddRaiz;
    private javax.swing.JComboBox comboboxPadre;
    private javax.swing.JLabel contenImg;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel label;
    private javax.swing.JLayeredPane panelImagen;
    private javax.swing.JTextField textHijo;
    // End of variables declaration//GEN-END:variables

}
