import com.sun.scenario.effect.impl.ImagePool;
import java.awt.Image;
import java.awt.image.ImageProducer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ArmandoPC
 */
public class ArbolForm extends javax.swing.JFrame {

    Familia arbol;
    ImageIcon Imagen = new ImageIcon();

    /**
     * Creates new form ArbolForm
     */
    public ArbolForm() {
        arbol = new Familia();
        initComponents();
        this.btnAddHijo.setEnabled(false);
        this.comboboxPadre.setEnabled(false);
        this.textHijo.setEnabled(false);
//        txtPane.setContentType("text/html");
//        ImageIcon Img = new ImageIcon("C:\\Users\\ArmandoPC\\Documents\\NetBeansProjects\\arbol-N-arios\\arbol.png");
//        this.panelImg.setIcon(Img);
//        Imagen = new Imagen();
//        this.panelImg.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        panelImagen = new javax.swing.JLayeredPane();
        label = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        comboboxPadre = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        textHijo = new javax.swing.JTextField();
        btnAddHijo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAddRaiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenLayout.createSequentialGroup()
                .addGap(0, 251, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelImagen.setLayer(label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBackground(new java.awt.Color(153, 153, 153));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Padre:");

        comboboxPadre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxPadreActionPerformed(evt);
            }
        });

        jLabel2.setText("Hijo:");

        btnAddHijo.setText("Añadir Hijo");
        btnAddHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHijoActionPerformed(evt);
            }
        });

        jLabel3.setText("Arbol Genealógico");

        btnAddRaiz.setText("Añadir Raiz");
        btnAddRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRaizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textHijo)
                    .addComponent(comboboxPadre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnAddHijo))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddRaiz)))
                .addGap(57, 57, 57))
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddHijo, btnAddRaiz});

        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btnAddHijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddRaiz)
                .addGap(161, 161, 161))
        );
        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(comboboxPadre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(textHijo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAddHijo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAddRaiz, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane2)
                    .addComponent(panelImagen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxPadreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboboxPadreActionPerformed

    private void btnAddHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHijoActionPerformed
        // TODO add your handling code here:
        String padre = this.comboboxPadre.getSelectedItem().toString();
        String hijo = this.textHijo.getText();
        if (hijo.length() > 0) {
            arbol.addHijoRecursivo(arbol.getRaiz(), hijo, padre);
            arbol.setListaPesona(new ArrayList<Persona>());
            arbol.verHijosRecursivo(arbol.getRaiz());
            this.LlenarCombo(arbol.getListaPesona());
            this.textHijo.setText("");
            try {
                arbol.generarArchivo(arbol.generateFileData(arbol.getRaiz()));
                if (arbol.GenerateImg()) {
//                    this.panelImagen.createImage(new ImageProducer("C:\\Users\\ArmandoPC\\Documents\\NetBeansProjects\\arbol.png"));
//                    ImageIcon h = new ImageIcon("C:\\Users\\ArmandoPC\\Documents\\NetBeansProjects\\arbol.png");
//                    this.panelImagen.getGraphics().drawImage(h.getImage(), 0, 0, null);
//                    this.panelImagen.setIcon(new ImageIcon("C:\\Users\\ArmandoPC\\Documents\\NetBeansProjects\\arbol.png"));
                    this.label.setIcon(new ImageIcon("C:\\Users\\ArmandoPC\\Documents\\NetBeansProjects\\arbol.png"));

//                    try {
//                        Thread.sleep(1500);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(ArbolForm.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                    this.txtPane.setText("");
//                    this.txtPane.setText("<html><head></head><img src=" + getClass().getResource("/recurso/arbol"+arbol.cambio+".png").toString() + "></html>");
//                    this.txtPane.repaint();
                }
            } catch (IOException ex) {
                Logger.getLogger(ArbolForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "Error al ingresar raiz");

        }

    }//GEN-LAST:event_btnAddHijoActionPerformed

    private void btnAddRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRaizActionPerformed
        // TODO add your handling code here:
        String raiz = JOptionPane.showInputDialog(this.getRootPane(), "Ingrese Raiz");
        if (raiz.length() > 0) {
            arbol.setRaiz(new Persona(raiz));
            this.btnAddHijo.setEnabled(true);
            this.btnAddRaiz.setEnabled(false);
            this.comboboxPadre.setEnabled(true);
            this.textHijo.setEnabled(true);
            arbol.verHijosRecursivo(arbol.getRaiz());
            this.LlenarCombo(arbol.getListaPesona());
            try {
                arbol.generarArchivo(arbol.generateFileData(arbol.getRaiz()));
                if (arbol.GenerateImg()) {
//                    try {
//                        Thread.sleep(3000);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(ArbolForm.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                    this.txtPane.setText("");
//                    this.txtPane.setText("<html><head></head><img src=" + getClass().getResource("/recurso/arbol"+arbol.cambio+".png").toString() + "></html>");
//                    this.txtPane.repaint();
                    this.label.setIcon(new ImageIcon("C:\\Users\\ArmandoPC\\Documents\\NetBeansProjects\\arbol.png"));
//                    this.label.setIcon(Imagen);
                }
//                arbol.GenerateImg();
//                this.txtPane.setText("<html><head></head><img src=" + getClass().getResource("/recurso/arbol.png").toString() + "></html>");
//                this.txtPane.repaint();
            } catch (IOException ex) {
                Logger.getLogger(ArbolForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "Error al ingresar raiz");
        }
    }//GEN-LAST:event_btnAddRaizActionPerformed

    public void LlenarCombo(List<Persona> g) {
        this.comboboxPadre.removeAllItems();
        for (Persona es : g) {
            this.comboboxPadre.addItem(es);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHijo;
    private javax.swing.JButton btnAddRaiz;
    private javax.swing.JComboBox comboboxPadre;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel label;
    private javax.swing.JLayeredPane panelImagen;
    private javax.swing.JTextField textHijo;
    // End of variables declaration//GEN-END:variables

}
